fix(scripts): import _thread instead of thread in rpi-pin356-power-py
Fix the following error when running the script:

Traceback (most recent call last):
  File "/recalbox/scripts/rpi-pin356-power.py", line 4, in <module>
    import thread
ModuleNotFoundError: No module named 'thread'

Signed-off-by: Wolfgang Wallner <wolfgang-wallner@gmx.at>