fix(scripts): use _thread instead of thread
This fixes the following error when running the script and pressing
Reset on a NESPi 4 case:

Button pressed
Button released
3
Traceback (most recent call last):
  File "/recalbox/scripts/rpi-pin356-power.py", line 79, in onoff_mode
    offreset(speed, shutdownstring)
  File "/recalbox/scripts/rpi-pin356-power.py", line 134, in offreset
    thread.start_new_thread( blink, (speed, ))
NameError: name 'thread' is not defined
Button released

Signed-off-by: Wolfgang Wallner <wolfgang-wallner@gmx.at>