fix(scripts): Use .encode() for passing a string in sendto()
This fixes the following error when running the script and pressing
Reset on a NESPi 4 case:

Button pressed
Button pressed
Button released
15
Traceback (most recent call last):
  File "/recalbox/scripts/rpi-pin356-power.py", line 66, in onoff_mode
    retroarch(nwcommand)
  File "/recalbox/scripts/rpi-pin356-power.py", line 165, in retroarch
    s.sendto(nwcommand, (IPADDR, PORTNUM))
TypeError: a bytes-like object is required, not 'str'
Button released

Signed-off-by: Wolfgang Wallner <wolfgang-wallner@gmx.at>