fix(scripts): open /proc/<pid>/cmdline in text mode
This fixes the following error when running the script and pressing
Reset on a NESPi 4 case:

Button pressed
Button pressed
Button released
3
1
Traceback (most recent call last):
  File "/recalbox/scripts/rpi-pin356-power.py", line 79, in onoff_mode
    offreset(speed, shutdownstring)
  File "/recalbox/scripts/rpi-pin356-power.py", line 144, in offreset
    if "emulationstation" in commandpath:
TypeError: a bytes-like object is required, not 'str'
Button released

Signed-off-by: Wolfgang Wallner <wolfgang-wallner@gmx.at>